---
- hosts: clients
  gather_facts: yes
  vars_files:
   - "defaults/secret.yaml"
   - "defaults/plain.yaml"
   - ["vars/{{ansible_facts['fqdn']}}.yaml", "vars/defaults.yaml"]
  remote_user: francesco
  become: yes
  tasks:
    #    - import_tasks: tasks/list_domains.yaml
      #    - import_tasks: tasks/create_acme_account.yaml
    #- import_tasks: tasks/install_acme.yaml
    - import_tasks: tasks/install_certbot.yaml

