---
- name: "List all acme accounts"
  delegate_to: 127.0.0.1
  uri: 
    url: "https://cert-manager.com/api/acme/v1/account?organizationId={{ organizationId }}"
    method: GET
    headers:
      Content-Type: application/json
      login: "{{ login }}"
      password: "{{ password }}"
      customerUri: "{{ customerUri }}"
  register: account_list  
- debug:
    msg: "checking acme account: {{ account_name }} ..."
  vars:
    accounts: "{{ account_list.json | json_query(jmesquery) }}"
    acme_account: "{{ accounts[0] }}"
    jmesquery: '[?"name"==`{{ account_name }}`]'
    #    jmesquery: '[?"name"==`{{ account_name }}`].id | [0]'
- name: "Expose acme accounts info"
  block:
  - name: "Create acme account block"
    block:
      - name: "Call create acme account api"
        uri:
          url: "https://cert-manager.com/api/acme/v1/account"
          method: POST
          headers:
            Content-Type: "application/json;charset=UTF-8"
            login: "{{ login }}"
            password: "{{ password }}"
            customerUri: "{{ customerUri }}"
          body: '{"name":"{{ account_name }}","acmeServer":"https://acme.sectigo.com/v2/OV","organizationId":"{{ organizationId }}"}'
          body_format: json
          status_code: [ 201 ]
        register: acme_account_details
      - debug:
          var: acme_account_details
      - name: "Update acme account with domains"
        uri:
          url: "https://cert-manager.com/api/acme/v1/account/{{ account_id}}/domains"
          method: POST
          headers:
            Content-Type: "application/json;charset=UTF-8"
            login: "{{ login }}"
            password: "{{ password }}"
            customerUri: "{{ customerUri }}"
            body: '{"domains":[{"name":"domain.ccmqa.com"},{"name":"sub.domain.ccmqa.com"}]}'
          body_format: json
          status_code: [ 201 ]
        vars:
          location: "{{ acme_account_details['location'] }}"
          account_id: "{{ location.split('/') | last }}"
    when: acme_account is falsy
  - name: "Extract acme account info block"
    set_fact:
      account_id: account_id
      hmac_key_id: hmac_key_id
      hmac_key: hmac_key
    vars:
      account_id: "{{ acme_account['id'] }}"
      hmac_key_id: "{{ acme_account['macId'] }}"
      hmac_key: "{{ acme_account['macKey'] }}"
    when: acme_account is truthy
  vars:
    accounts: "{{ account_list.json | json_query(jmesquery) }}"
    acme_account: "{{ accounts[0] }}"
    jmesquery: '[?"name"==`{{ account_name }}`]'

